### ISSUE TITLE
Only enqueuer and TA should be able to delete an entry

### ISSUE THREAD

**Issue by hmontero1205** [hmontero1205/Qpp#7]

**Comment by hmontero1205** [comment]
Make it such that the 'X' button only shows up for TAs.

We'll add on to this later so that the enqueuer can delete their own entries.

**Comment by emesterhazy** [comment]
Partially addressed by #10 which made it so that only the TA that created the OH can remove entries.

TODO:
- Allow both non-logged in and logged in students to delete entries they created
- Render the queue entry cards on the server and only render the X button if the user is able to delete the entry.
